In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\HP\Downloads\fraud_risk_management\indian_banking_transactions.csv')

In [3]:
df.head()

,transaction_id,customer_id,transaction_date,transaction_time,account_type,transaction_type,transaction_amount,transaction_direction,account_balance,merchant_category,state,credit_score,has_loan,loan_type,emi_amount,transaction_status,channel,kyc_status,is_fraud,transaction_hour
0,TXN000000001,CUST015796,2019-01-01,15:28,Current,UPI,1820.17,Debit,609365.31,Food & Dining,Maharashtra,764,0,NaN,0.00,Success,Branch,Verified,0,15
1,TXN000000002,CUST000861,2019-01-01,03:00,Current,UPI,392.67,Credit,14451.14,Education,West Bengal,630,0,NaN,0.00,Success,Mobile_App,Verified,0,3
2,TXN000000003,CUST076821,2019-01-01,18:03,Fixed Deposit,POS,1255.97,Debit,47621.87,Utilities,Punjab,813,1,Home,1433.91,Success,Mobile_App,Verified,0,18
3,TXN000000004,CUST054887,2019-01-01,08:03,Savings,UPI,2580.68,Debit,34467.85,Travel,Karnataka,628,1,Personal,6280.35,Success,API,Verified,0,8
4,TXN000000005,CUST006266,2019-01-01,14:23,Fixed Deposit,UPI,2573.80,Debit,26617.40,Utilities,West Bengal,767,0,NaN,0.00,Success,API,Verified,0,14

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   transaction_id         550000 non-null  str
 1   customer_id            550000 non-null  str
 2   transaction_date       550000 non-null  str
 3   transaction_time       550000 non-null  str
 4   account_type           550000 non-null  str
 5   transaction_type       550000 non-null  str
 6   transaction_amount     550000 non-null  float64
 7   transaction_direction  550000 non-null  str
 8   account_balance        550000 non-null  float64
 9   merchant_category      550000 non-null  str
 10  state                  550000 non-null  str
 11  credit_score           550000 non-null  int64
 12  has_loan               550000 non-null  int64
 13  loan_type              172866 non-null  str
 14  emi_amount             550000 non-null  float64
 15  transaction_status     550000 non-null  str
 16  channel                550000 non-null  str
 17  kyc_status             550000 non-null  str
 18  is_fraud               550000 non-null  int64
 19  transaction_hour       550000 non-null  int64
dtypes: float64(3), int64(4), str(13)
memory usage: 83.9 MB

In [5]:
df.isnull().sum()

transaction_id                0
customer_id                   0
transaction_date              0
transaction_time              0
account_type                  0
transaction_type              0
transaction_amount            0
transaction_direction         0
account_balance               0
merchant_category             0
state                         0
credit_score                  0
has_loan                      0
loan_type                377134
emi_amount                    0
transaction_status            0
channel                       0
kyc_status                    0
is_fraud                      0
transaction_hour              0
dtype: int64

In [6]:
print(((df["has_loan"] == 1) & (df["loan_type"].isnull())).sum())

19422

In [7]:
df.loc[df["has_loan"] == 1, "loan_type"].value_counts(dropna=False)

loan_type
Personal     47810
Home         38252
Auto         29219
Business     28863
NaN          19422
Education    19074
Gold          9648
Name: count, dtype: int64

In [8]:
df.loc[(df["has_loan"] == 0) & (df["loan_type"].isnull()), "loan_type"] = "No Loan"

In [9]:
df.loc[(df["has_loan"] == 1) & (df["loan_type"].isnull()), "loan_type"] = "Unknown"

In [10]:
df["loan_type"].value_counts(dropna=False)

loan_type
No Loan      357712
Personal      47810
Home          38252
Auto          29219
Business      28863
Unknown       19422
Education     19074
Gold           9648
Name: count, dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["transaction_id"].duplicated().sum()

np.int64(0)

In [13]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"])

In [14]:
df["transaction_date"].dtype

dtype('<M8[us]')

In [15]:
(df["transaction_time"].str[:2].astype(int) != df["transaction_hour"]).sum()

np.int64(0)

In [16]:
df["transaction_type"].value_counts()

transaction_type
UPI               153986
IMPS               77038
NEFT               66615
POS                60278
ATM_Withdrawal     55106
Net_Banking        38458
RTGS               32964
Auto_Debit         27418
Cheque             21711
Credit_Card        16426
Name: count, dtype: int64

In [17]:
df["transaction_direction"].value_counts()

transaction_direction
Debit     370394
Credit    179606
Name: count, dtype: int64

In [18]:
df["transaction_amount"].describe()

count    5.500000e+05
mean     2.990709e+04
std      1.396101e+05
min      2.400000e+00
25%      7.630375e+02
50%      2.035735e+03
75%      8.557497e+03
max      1.000000e+07
Name: transaction_amount, dtype: float64

In [19]:
df["account_balance"].describe()

count    5.500000e+05
mean     8.455012e+04
std      1.709146e+05
min      5.000000e+02
25%      1.515778e+04
50%      3.642287e+04
75%      8.760704e+04
max      5.000000e+06
Name: account_balance, dtype: float64

In [20]:
df["credit_score"].describe()

count    550000.000000
mean        599.807009
std         173.054597
min         300.000000
25%         450.000000
50%         600.000000
75%         750.000000
max         899.000000
Name: credit_score, dtype: float64

In [21]:
df["emi_amount"].describe()

count    550000.000000
mean       2365.859974
std        4973.546080
min           0.000000
25%           0.000000
50%           0.000000
75%        3115.030000
max      153325.740000
Name: emi_amount, dtype: float64

In [22]:
df.groupby("has_loan")["emi_amount"].describe()

,count,mean,std,min,25%,50%,75%,max
has_loan,,,,,,,,
0,357712.0,0.000000,0.000000,0.00,0.00,0.000,0.0000,0.00
1,192288.0,6767.052471,6400.753728,185.94,2865.13,4903.945,8417.0925,153325.74

In [23]:
df["is_fraud"].value_counts()

is_fraud
0    545127
1      4873
Name: count, dtype: int64

In [24]:
df["is_fraud"].value_counts(normalize=True) * 100

is_fraud
0    99.114
1     0.886
Name: proportion, dtype: float64

In [25]:
pd.crosstab(df["transaction_status"], df["is_fraud"], normalize="index") * 100

is_fraud                    0         1
transaction_status
Failed              99.064141  0.935859
Pending             99.048850  0.951150
Reversed            99.092477  0.907523
Success             99.118019  0.881981

In [26]:
pd.crosstab(df["transaction_type"], df["is_fraud"])

is_fraud               0     1
transaction_type
ATM_Withdrawal     54650   456
Auto_Debit         27231   187
Cheque             21455   256
Credit_Card        16286   140
IMPS               76414   624
NEFT               66034   581
Net_Banking        38132   326
POS                59797   481
RTGS               32353   611
UPI               152775  1211

In [27]:
fraud_rate_by_type = (
    df.groupby("transaction_type")["is_fraud"]
      .mean()
      .mul(100)
      .sort_values(ascending=False)
)

fraud_rate_by_type

transaction_type
RTGS              1.853537
Cheque            1.179126
NEFT              0.872176
Credit_Card       0.852307
Net_Banking       0.847678
ATM_Withdrawal    0.827496
IMPS              0.809990
POS               0.797969
UPI               0.786435
Auto_Debit        0.682034
Name: is_fraud, dtype: float64

In [28]:
df["channel"].value_counts()

channel
Mobile_App      208368
Web             121010
ATM              66177
POS_Terminal     60853
Branch           54957
API              38635
Name: count, dtype: int64

In [29]:
df.groupby("channel")["is_fraud"].mean().mul(100).sort_values(ascending=False)

channel
Branch          0.946194
POS_Terminal    0.915321
API             0.895561
Web             0.892488
Mobile_App      0.868176
ATM             0.847727
Name: is_fraud, dtype: float64

In [30]:
df.groupby("transaction_hour")["is_fraud"].mean().mul(100)

transaction_hour
0     0.946441
1     0.790720
2     0.844327
3     0.921961
4     0.875141
5     0.857244
6     0.928874
7     0.948568
8     0.847603
9     0.891478
10    1.008178
11    0.849883
12    0.864969
13    0.792952
14    0.917069
15    0.941268
16    0.939416
17    0.866498
18    0.881467
19    0.893561
20    0.788732
21    0.941043
22    0.835364
23    0.890233
Name: is_fraud, dtype: float64

In [31]:
df.groupby("merchant_category")["is_fraud"].mean().mul(100).sort_values(ascending=False)

merchant_category
Peer Transfer    0.934121
Investment       0.920380
E-Commerce       0.916610
Fuel             0.916594
Entertainment    0.909174
Healthcare       0.908678
Salary           0.901290
Retail           0.897552
Travel           0.878285
Insurance        0.867393
Education        0.862605
Real Estate      0.860047
Food & Dining    0.859866
Utilities        0.837330
Government       0.777956
Name: is_fraud, dtype: float64

In [32]:
df.groupby("state")["is_fraud"].mean().mul(100).sort_values(ascending=False)

state
UP             0.948421
West Bengal    0.939704
Karnataka      0.914439
Maharashtra    0.894744
Delhi          0.889373
Telangana      0.886918
Tamil Nadu     0.882267
Gujarat        0.879594
Rajasthan      0.782440
Punjab         0.761145
Name: is_fraud, dtype: float64

In [33]:
df.groupby("is_fraud")["transaction_amount"].describe()

,count,mean,std,min,25%,50%,75%,max
is_fraud,,,,,,,,
0,545127.0,29106.685733,135379.522408,2.40,762.085,2030.99,8508.705,10000000.00
1,4873.0,119446.211798,376261.471630,8.65,895.840,2691.95,19189.240,6751663.36

In [34]:
df.groupby("is_fraud")["account_balance"].describe()

,count,mean,std,min,25%,50%,75%,max
is_fraud,,,,,,,,
0,545127.0,84522.096647,170832.721485,500.0,15157.71,36424.36,87572.17,5000000.00
1,4873.0,87684.447492,179828.304132,500.0,15164.35,36238.03,91199.12,4273789.13